runstack:
	g++ LinkedList.h
	g++ stack.h
	g++ -c stack.cpp
	g++ -c LinkedList.cpp
	g++ -c stack_driver.cpp
	g++ LinkedList.cpp stack.cpp stack_driver.cpp

	#COMPILATION WITHOUT ERROR. ./a.out "stack_sample file name" to run
