singlell:
	g++ single_LL_header.h
	g++ -c single_LL_functions.cpp
	g++ -c driver_single_LL.cpp
	g++ single_LL_header.h single_LL_functions.cpp driver_single_LL.cpp
	
	#compilation without ERROR; ./a.out to RUN	
