run:
	g++ Queue.h
	g++ MultiQueue.h
	g++ -c Queue.cpp
	g++ -c MultiQueue.cpp
	g++ -c driver_multiq.cpp
	g++ Queue.cpp MultiQueue.cpp driver_multiq.cpp
	
	#COMPILATION WITHOUT ERROR. $ ./a.out "input_file_name" "no_of_task_in_input_file" to run
